# Note that this will create num_of_images in image dir * num_random_search_points config files.
image_dir: "images/compare"
num_random_search_points: null
hyperparameters:
  paths:
    stage_1_clip_scores_output_path: ["results/compare/compare.csv"]
    stage_1_result_images_output_path: ["results/compare/ours/"]
    stage_2_clip_scores_output_path: ["results/compare/stage2/clip_scores.csv"]
    stage_2_mesh_images_output_path: ["results/compare/stage2/mesh_images/ours/"]

  dreamgaussian:
    export_mesh_for_stage_1: [True]  # we need this as input for stage 2
    stage_1_result_images_output_path: ["results/compare/ours/"]
    save_images: [True] # required for computing clip scores.
    stage_2_gaussian_properties_csv_path: ["results/compare/stage2/gaussians/ours/properties.csv"]

    # best config found was e0.0001c1.0o0.001
    regularize:
      elongation: [0.0001] # also always use 0 to compare to baseline dg.
      compactness: [1.0] # but this leads to 2**3 = 8 configs rather than 4. So better just use two jobs or move this logic into the run_results.job
      opacity: [0.001]


