#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/master-thesis-ds/
git pull

cd $HOME/master-thesis-ds/repos/gaussian-splatting

conda env create --file environment.yml
source activate gaussian_splatting

