#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pipeline
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=logs/slurm_output_%A.out

module purge
module load 2022
module load CUDA/11.8.0
module load Anaconda3/2022.05

set e

cd $HOME/master-thesis-ds/
git pull

source activate dreamgaussianV2

# install own package
cd ptdraft
pip install -e .
cd ..

# pip install git+https://github.com/openai/CLIP.git
# pip install clip-score

python pipeline.py --config configs/grid_search/1.yaml

# git add .
# git commit -m "auto commit from snellius"
# git push


