#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=RunDreamGaussian
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load CUDA/11.8.0
module load Anaconda3/2022.05

cd $HOME/master-thesis-ds/
git pull

cd $HOME/master-thesis-ds/repos/LGM

source activate lgm
# python infer.py big --workspace workspace_test --resume workspace/model.safetensors --test_path data_test





