dreamgaussian:
  H: 800
  W: 800
  anneal_timestep: true
  batch_size: 1
  coarse_mesh_output_dir: results/mesh/coarse/
  densification_interval: 100
  densify_grad_threshold: 0.01
  density_end_iter: 3000
  density_start_iter: 100
  density_thresh: 1
  elevation: 0
  export_mesh_for_stage_1: true
  feature_lr: 0.01
  force_cuda_rast: false
  fovy: 49.1
  generate_gaussian_distribution_plots: false
  generate_image_progressions: false
  geom_lr: 0.0001
  imagedream: false
  input: null
  input_image_path: images/grid_search/image-2.png
  invert_bg_prob: 0.5
  iters: 500
  iters_refine: 50
  lambda_sd: 0
  lambda_zero123: 1
  load: null
  max_ver: 30
  mesh_format: obj
  min_ver: -30
  mvdream: false
  num_pts: 5000
  opacity_lr: 0.05
  opacity_reset_interval: 700
  outdir: results/dream_gaussian/
  percent_dense: 0.01
  position_lr_delay_mult: 0.02
  position_lr_final: 2.0e-05
  position_lr_init: 0.001
  position_lr_max_steps: 500
  preprocessing_output_path: results/preprocessing/
  radius: 2
  ref_size: 512
  regularize:
    compactness: 10.0
    elongation: 0.1
    opacity: 0.1
  rotation_lr: 0.005
  save_geo_plus_texture: true
  save_images: true
  save_model: false
  scaling_lr: 0.005
  sh_degree: 0
  stable_zero123: false
  stage_1_images_output_path: results/dream_gaussian/stage_1/
  stage_1_result_images_output_path: results/stage_1/3images/
  stage_2_mesh_output_path: results/mesh/stage_2/
  texture_lr: 0.2
  train_geo: false
  warmup_rgb_loss: true
paths:
  dream_gaussian_repo_path: repos/dreamgaussian/
  dream_gaussian_results_path: results/dream_gaussian/
  image_progression_output_path: results/image_progression/
  input_image_path: images/grid_search/image-2.png
  model_output_path: results/dream_gaussian/model/
  preprocessing_output_path: results/preprocessing/
  stage_1_clip_scores_output_path: results/stage_1/grid_search_clip_scores_v2.csv
  stage_1_images_output_path: results/dream_gaussian/stage_1/
  stage_1_result_images_output_path: results/stage_1/3images/
  stage_2_clip_scores_output_path: results/stage_2/grid_search_clip_scores_v2.csv
  stage_2_mesh_output_path: results/mesh/stage_2/
preprocess:
  border_ratio: 0.2
  recenter: true
  size: 512
