#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/master-thesis-ds/repos/dreamgaussian
conda env export > environment_snellius_specific.yml
conda env export --no-builds | grep -v "prefix" > environment_no_builds.yml
conda list -e > conda_requirements.txt
