name: dreamgaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.8
  - pytorch=1.13
  - torchaudio
  - torchvision
  - tqdm
  - pip
pip:
- rich
- ninja
- numpy
- pandas
- scipy
- scikit-learn
- matplotlib
- opencv-python
- imageio
- imageio-ffmpeg
- omegaconf

- torch
- einops
- plyfile
- pygltflib

# for gui
- dearpygui

# for stable-diffusion
- huggingface_hub
- diffusers
- accelerate
- transformers

# for dmtet and mesh export
- xatlas
- trimesh
- PyMCubes
- pymeshlab

- rembg[gpu,cli]

# gradio demo
- gradio
