name: dreamgaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - python=3.8
  - pip
  - pip:
    - torch == 2.1.0+cu121
    - tqdm
    - rich
    - ninja
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
    - opencv-python
    - imageio
    - imageio-ffmpeg
    - omegaconf
    - torch
    - pygltflib
    - dearpygui
    - huggingface_hub
    - diffusers
    - accelerate
    - transformers
    - xatlas
    - trimesh
    - PyMCubes
    - pymeshlab
    - rembg[gpu,cli]
    - gradio
    - plyfile